# 此程序用于根据Halcon标定板的参数生成对应的descr文件

def main():
    print('请输入图案边长mm:')
    pattern = input()
    s = pattern * pattern
    file_name = './ctlab_' + str(s) + 'mm.descr'
    file = open(file_name, 'w')
    file.write('# Description of the standard calibration plate\n # used for the CCD camera calibration in HALCON # (generated by gen_caltab)')

    print('请输入纵列数:')
    r = input()
    c = r

    # 计算圆形图案半径
    radius = pattern / 8 / 4

    w = radius


if __name__ == '__main__':
    main()
